<?php
namespace App\Controller;

use Cake\Controller\Controller;
use Cake\Event\Event;
use Cake\ORM\TableRegistry;

class SignUpController extends Controller
{
//    public function beforeRender(Event $event)
//    {
//        $this->layout = 'faka';
//        return parent::beforeRender($event); // TODO: Change the autogenerated stub
//    }
    public function index()
    {
        $this->layout = 'faka';
        if ($this->request->is('post')) {
            $assignment = TableRegistry::get('Users');
            $query = $assignment->find();
            $query->select(['count' => $query->func()->count('id')]);
            $query->where(['Users.email'=> $this->request->data('email')]);
            $assignment = $query->toArray();
            $assignment_count = $assignment[0]->count;
            if($assignment_count>0) {
                $this->set('message', 'Sorry!Same registration exits.Try another.');
            }
            else{
                $usersTable = TableRegistry::get('Users');
                $users = $usersTable->newEntity();
                $users->name = $this->request->data('name');
                $users->mobile = $this->request->data('phone');
                $users->email = $this->request->data('email');
                $users->password = md5($this->request->data('password'));
                $users->terms = $this->request->data('terms');
                $usersTable->save($users);
                if ($usersTable->save($users)) {
                    $this->set('message', 'Congrats!Registration is successfull.Please Login.');
                    $this -> render('/Signup/login');
                }
                else{
                    $this->set('message', 'Registration is failed.');
                }
            }
        }
    }
    public function login()
    {
        $this->layout = 'faka';
        if ($this->request->is('post')) {
            $assignment = TableRegistry::get('Users');
            $query = $assignment->find();
            $query->select(['count' => $query->func()->count('id')]);
            $query->where([
                'Users.email'=> $this->request->data('email'),
                'Users.password'=> md5($this->request->data('password'))
            ]);
            $assignment = $query->toArray();
            $assignment_count = $assignment[0]->count;
            if($assignment_count==1) {
                $this->layout = 'mainLayout';
                $this -> render('/Home/index');
            }
            else{
                $this->set('message', 'Email and Password not correct.');
            }
        }
    }

}
